"""
Question Data Models

This module defines Pydantic models for questions generated by LLMs
in the Mentor AI EdTech Platform. These models handle validation of
questions for different exam types (JEE Main, JEE Advanced, NEET).

Models:
- QuestionOptions: Model for MCQ options
- QuestionMetadata: Metadata about question generation
- Question: Base question model with all fields
- QuestionFilter: Filter criteria for question queries
- QuestionBatch: Batch of questions with statistics
- GeneratedQuestionsResponse: Response containing multiple questions

Author: Mentor AI Team
Version: 1.0.0
"""

from datetime import datetime
from typing import Dict, List, Optional, Literal, Union, Any
from pydantic import BaseModel, Field, field_validator, ConfigDict


class QuestionOptions(BaseModel):
    """
    Model for MCQ options.
    
    Represents the four options (A, B, C, D) for a multiple choice question.
    
    Attributes:
        A: First option text
        B: Second option text
        C: Third option text
        D: Fourth option text
    
    Example:
        >>> options = QuestionOptions(
        ...     A="Newton's First Law",
        ...     B="Newton's Second Law",
        ...     C="Newton's Third Law",
        ...     D="Law of Gravitation"
        ... )
    """
    
    A: str = Field(
        ...,
        description="Option A text",
        min_length=1
    )
    
    B: str = Field(
        ...,
        description="Option B text",
        min_length=1
    )
    
    C: str = Field(
        ...,
        description="Option C text",
        min_length=1
    )
    
    D: str = Field(
        ...,
        description="Option D text",
        min_length=1
    )
    
    @field_validator("A", "B", "C", "D")
    @classmethod
    def validate_option_not_empty(cls, v: str) -> str:
        """
        Validate that option text is not empty or whitespace only.
        
        Args:
            v: Option text to validate
        
        Returns:
            str: Validated and stripped option text
        
        Raises:
            ValueError: If option is empty or whitespace only
        """
        if not v or not v.strip():
            raise ValueError("Option text cannot be empty")
        return v.strip()
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "A": "0",
                "B": "1",
                "C": "2",
                "D": "3"
            }
        }
    )


class QuestionMetadata(BaseModel):
    """
    Metadata about question generation and validation.
    
    This model stores information about how the question was generated,
    its quality score, and any validation issues.
    
    Attributes:
        generation_method: How the question was generated (RAG, manual, etc.)
        vector_search_score: Relevance score from vector search (if applicable)
        validation_score: Overall validation quality score (0-100)
        quality_issues: List of quality issues found during validation
        source_context: Optional syllabus or context used for generation
        generated_by: Model or system that generated the question
        generation_timestamp: When the question was generated
    
    Example:
        >>> metadata = QuestionMetadata(
        ...     generation_method="RAG",
        ...     vector_search_score=0.92,
        ...     validation_score=85,
        ...     quality_issues=[],
        ...     source_context="JEE Main Syllabus - Calculus",
        ...     generated_by="gemini-2.5-flash-lite"
        ... )
    """
    
    generation_method: str = Field(
        default="RAG",
        description="Method used to generate question (RAG, manual, etc.)"
    )
    
    vector_search_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Relevance score from vector search (0.0 to 1.0)"
    )
    
    validation_score: int = Field(
        default=0,
        ge=0,
        le=100,
        description="Overall validation quality score (0-100)"
    )
    
    quality_issues: List[str] = Field(
        default_factory=list,
        description="List of quality issues found during validation"
    )
    
    source_context: Optional[str] = Field(
        default=None,
        description="Syllabus or context used for generation"
    )
    
    generated_by: str = Field(
        default="gemini-2.5-flash-lite",
        description="Model or system that generated the question"
    )
    
    generation_timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="When the question was generated"
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "generation_method": "RAG",
                "vector_search_score": 0.92,
                "validation_score": 85,
                "quality_issues": [],
                "source_context": "JEE Main Syllabus - Limits and Continuity",
                "generated_by": "gemini-2.5-flash-lite",
                "generation_timestamp": "2024-11-27T10:30:00Z"
            }
        }
    )


class Question(BaseModel):
    """
    Base model for a generated question.
    
    This model represents a complete question with all required fields
    for different exam types. Includes validation for correctness.
    
    Attributes:
        question: The question text
        options: Dictionary of options (for MCQ types)
        correct_answer: The correct answer (A/B/C/D for MCQ, or list for multiple correct, or int for numerical)
        explanation: Detailed explanation of the solution
        difficulty: Difficulty level (easy, medium, hard)
        topic: Topic or chapter name
        question_type: Type of question
        marks: Marks for the question (default: 4)
        estimated_time_minutes: Estimated time to solve (default: 3)
    
    Example:
        >>> question = Question(
        ...     question="What is the derivative of sin(x)?",
        ...     options=QuestionOptions(
        ...         A="cos(x)",
        ...         B="-cos(x)",
        ...         C="sin(x)",
        ...         D="-sin(x)"
        ...     ),
        ...     correct_answer="A",
        ...     explanation="The derivative of sin(x) is cos(x) by standard differentiation rules.",
        ...     difficulty="easy",
        ...     topic="Calculus - Differentiation",
        ...     question_type="single_correct"
        ... )
    """
    
    id: Optional[str] = Field(
        default=None,
        description="Firestore document ID"
    )
    
    question: str = Field(
        ...,
        description="The question text (supports LaTeX)",
        min_length=10
    )
    
    options: Optional[Union[QuestionOptions, Dict[str, str]]] = Field(
        None,
        description="Options for MCQ questions (A, B, C, D)"
    )
    
    correct_answer: Union[str, List[str], int] = Field(
        ...,
        description="Correct answer(s). String (A/B/C/D) for single correct, "
                   "List of strings for multiple correct, int for numerical"
    )
    
    explanation: str = Field(
        ...,
        description="Detailed explanation of the solution",
        min_length=20
    )
    
    difficulty: Literal["easy", "medium", "hard"] = Field(
        ...,
        description="Difficulty level: easy, medium, or hard"
    )
    
    topic: str = Field(
        ...,
        description="Topic or chapter name",
        min_length=3
    )
    
    subtopic: Optional[str] = Field(
        default=None,
        description="Optional subtopic"
    )
    
    exam_type: Literal["JEE_MAIN", "JEE_ADVANCED", "NEET"] = Field(
        ...,
        description="Type of entrance exam"
    )
    
    subject: Literal["Physics", "Chemistry", "Math", "Biology"] = Field(
        ...,
        description="Subject area"
    )
    
    question_type: Literal["single_correct", "multiple_correct", "numerical", "matrix_match"] = Field(
        default="single_correct",
        description="Type of question"
    )
    
    metadata: QuestionMetadata = Field(
        default_factory=QuestionMetadata,
        description="Question generation and validation metadata"
    )
    
    marks: int = Field(
        default=4,
        description="Marks assigned to this question",
        ge=1,
        le=10
    )
    
    estimated_time_minutes: int = Field(
        default=3,
        description="Estimated time to solve in minutes",
        ge=1,
        le=30
    )
    
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Question creation timestamp"
    )
    
    @field_validator("question")
    @classmethod
    def validate_question_text(cls, v: str) -> str:
        """
        Validate question text is not empty and properly formatted.
        
        Args:
            v: Question text to validate
        
        Returns:
            str: Validated and cleaned question text
        
        Raises:
            ValueError: If question is empty or too short
        """
        if not v or not v.strip():
            raise ValueError("Question text cannot be empty")
        
        cleaned = v.strip()
        
        if len(cleaned) < 10:
            raise ValueError("Question text must be at least 10 characters long")
        
        return cleaned
    
    @field_validator("explanation")
    @classmethod
    def validate_explanation(cls, v: str) -> str:
        """
        Validate explanation is detailed enough.
        
        Args:
            v: Explanation text to validate
        
        Returns:
            str: Validated and cleaned explanation
        
        Raises:
            ValueError: If explanation is too short
        """
        if not v or not v.strip():
            raise ValueError("Explanation cannot be empty")
        
        cleaned = v.strip()
        
        if len(cleaned) < 20:
            raise ValueError("Explanation must be at least 20 characters long")
        
        return cleaned
    
    @field_validator("correct_answer")
    @classmethod
    def validate_correct_answer(cls, v: Union[str, List[str], int], info) -> Union[str, List[str], int]:
        """
        Validate correct answer based on question type.
        
        Args:
            v: Correct answer to validate
            info: Validation context
        
        Returns:
            Union[str, List[str], int]: Validated correct answer
        
        Raises:
            ValueError: If answer format is invalid for question type
        """
        question_type = info.data.get("question_type", "single_correct")
        
        if question_type == "single_correct":
            # Must be a single string (A, B, C, or D)
            if not isinstance(v, str):
                raise ValueError("Single correct answer must be a string (A, B, C, or D)")
            
            v_upper = v.strip().upper()
            if v_upper not in ["A", "B", "C", "D"]:
                raise ValueError(f"Single correct answer must be A, B, C, or D. Got: {v}")
            
            return v_upper
        
        elif question_type == "multiple_correct":
            # Must be a list of strings
            if not isinstance(v, list):
                raise ValueError("Multiple correct answer must be a list of strings")
            
            if len(v) == 0:
                raise ValueError("Multiple correct answer list cannot be empty")
            
            # Validate each answer
            validated = []
            for ans in v:
                if not isinstance(ans, str):
                    raise ValueError(f"Each answer must be a string. Got: {type(ans)}")
                
                ans_upper = ans.strip().upper()
                if ans_upper not in ["A", "B", "C", "D"]:
                    raise ValueError(f"Each answer must be A, B, C, or D. Got: {ans}")
                
                validated.append(ans_upper)
            
            # Remove duplicates and sort
            return sorted(list(set(validated)))
        
        elif question_type == "numerical":
            # Must be an integer between 0 and 9999
            if not isinstance(v, int):
                # Try to convert if it's a string
                if isinstance(v, str):
                    try:
                        v = int(v)
                    except ValueError:
                        raise ValueError(f"Numerical answer must be an integer. Got: {v}")
                else:
                    raise ValueError(f"Numerical answer must be an integer. Got: {type(v)}")
            
            if v < 0 or v > 9999:
                raise ValueError(f"Numerical answer must be between 0 and 9999. Got: {v}")
            
            return v
        
        # For other types, return as-is
        return v
    
    @field_validator("options")
    @classmethod
    def validate_options(cls, v: Optional[Union[QuestionOptions, Dict[str, str]]], info) -> Optional[Union[QuestionOptions, Dict[str, str]]]:
        """
        Validate options based on question type.
        
        Args:
            v: Options to validate
            info: Validation context
        
        Returns:
            Optional[Union[QuestionOptions, Dict[str, str]]]: Validated options
        
        Raises:
            ValueError: If options are invalid for question type
        """
        question_type = info.data.get("question_type", "single_correct")
        
        # MCQ types require options
        if question_type in ["single_correct", "multiple_correct"]:
            if v is None:
                raise ValueError(f"Options are required for {question_type} questions")
            
            # Convert dict to QuestionOptions if needed
            if isinstance(v, dict):
                # Validate all keys exist
                required_keys = {"A", "B", "C", "D"}
                actual_keys = set(v.keys())
                
                if actual_keys != required_keys:
                    raise ValueError(f"Options must have exactly A, B, C, D keys. Got: {actual_keys}")
                
                # Validate all values are non-empty strings
                for key, value in v.items():
                    if not isinstance(value, str) or not value.strip():
                        raise ValueError(f"Option {key} must be a non-empty string")
                
                # Convert to QuestionOptions
                try:
                    v = QuestionOptions(**v)
                except Exception as e:
                    raise ValueError(f"Invalid options format: {e}")
            
            # Validate options are distinct
            if isinstance(v, QuestionOptions):
                option_values = [v.A, v.B, v.C, v.D]
                # Check for duplicates (case-insensitive)
                lower_values = [val.lower().strip() for val in option_values]
                if len(lower_values) != len(set(lower_values)):
                    raise ValueError("Options must be distinct (no duplicates)")
        
        elif question_type == "numerical":
            # Numerical questions should not have options
            if v is not None:
                raise ValueError("Numerical questions should not have options")
        
        return v
    
    def to_dict(self) -> Dict[str, Any]:
        """
        Convert Question to dictionary for Firestore storage.
        
        Returns:
            Dict[str, Any]: Dictionary representation suitable for Firestore
        
        Example:
            >>> question = Question(...)
            >>> firestore_data = question.to_dict()
            >>> db.collection('questions').add(firestore_data)
        """
        data = self.model_dump(mode='json')
        
        # Convert QuestionOptions to dict if present
        if isinstance(self.options, QuestionOptions):
            data['options'] = {
                'A': self.options.A,
                'B': self.options.B,
                'C': self.options.C,
                'D': self.options.D
            }
        
        # Convert datetime objects to ISO format strings
        if isinstance(data.get('created_at'), datetime):
            data['created_at'] = self.created_at.isoformat()
        
        if isinstance(data.get('metadata'), dict):
            if isinstance(data['metadata'].get('generation_timestamp'), datetime):
                data['metadata']['generation_timestamp'] = self.metadata.generation_timestamp.isoformat()
        
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Question':
        """
        Create Question from Firestore dictionary.
        
        Args:
            data: Dictionary from Firestore document
        
        Returns:
            Question: Question instance
        
        Example:
            >>> doc = db.collection('questions').document('abc123').get()
            >>> question = Question.from_dict(doc.to_dict())
        """
        # Convert ISO format strings back to datetime
        if isinstance(data.get('created_at'), str):
            data['created_at'] = datetime.fromisoformat(data['created_at'])
        
        if isinstance(data.get('metadata'), dict):
            if isinstance(data['metadata'].get('generation_timestamp'), str):
                data['metadata']['generation_timestamp'] = datetime.fromisoformat(
                    data['metadata']['generation_timestamp']
                )
            data['metadata'] = QuestionMetadata(**data['metadata'])
        
        # Convert options dict to QuestionOptions if present
        if data.get('options') and isinstance(data['options'], dict):
            data['options'] = QuestionOptions(**data['options'])
        
        return cls(**data)
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "q_abc123",
                "question": "What is the derivative of sin(2x)?",
                "options": {
                    "A": "cos(2x)",
                    "B": "2cos(2x)",
                    "C": "-2sin(2x)",
                    "D": "2sin(2x)"
                },
                "correct_answer": "B",
                "explanation": "Using chain rule: d/dx[sin(2x)] = cos(2x) × 2 = 2cos(2x)",
                "difficulty": "easy",
                "topic": "Calculus - Differentiation",
                "subtopic": "Chain Rule",
                "exam_type": "JEE_MAIN",
                "subject": "Math",
                "question_type": "single_correct",
                "metadata": {
                    "generation_method": "RAG",
                    "vector_search_score": 0.92,
                    "validation_score": 85,
                    "quality_issues": [],
                    "source_context": "JEE Main Syllabus",
                    "generated_by": "gemini-2.5-flash-lite",
                    "generation_timestamp": "2024-11-27T10:30:00Z"
                },
                "marks": 4,
                "estimated_time_minutes": 2,
                "created_at": "2024-11-27T10:30:00Z"
            }
        }
    )


class QuestionFilter(BaseModel):
    """
    Filter criteria for querying questions.
    
    This model defines optional filters that can be applied when
    retrieving questions from the database.
    
    Attributes:
        exam_type: Filter by exam type
        subject: Filter by subject
        topic: Filter by topic
        difficulty: Filter by difficulty level
        min_quality_score: Minimum validation score (0-100)
        question_type: Filter by question type
    
    Example:
        >>> filters = QuestionFilter(
        ...     exam_type="JEE_MAIN",
        ...     subject="Math",
        ...     difficulty="medium",
        ...     min_quality_score=80
        ... )
    """
    
    exam_type: Optional[Literal["JEE_MAIN", "JEE_ADVANCED", "NEET"]] = Field(
        default=None,
        description="Filter by exam type"
    )
    
    subject: Optional[Literal["Physics", "Chemistry", "Math", "Biology"]] = Field(
        default=None,
        description="Filter by subject"
    )
    
    topic: Optional[str] = Field(
        default=None,
        description="Filter by topic"
    )
    
    difficulty: Optional[Literal["easy", "medium", "hard"]] = Field(
        default=None,
        description="Filter by difficulty level"
    )
    
    min_quality_score: Optional[int] = Field(
        default=None,
        ge=0,
        le=100,
        description="Minimum validation quality score (0-100)"
    )
    
    question_type: Optional[Literal["single_correct", "multiple_correct", "numerical", "matrix_match"]] = Field(
        default=None,
        description="Filter by question type"
    )
    
    @field_validator("min_quality_score")
    @classmethod
    def validate_quality_score(cls, v: Optional[int]) -> Optional[int]:
        """Validate quality score is in valid range."""
        if v is not None and (v < 0 or v > 100):
            raise ValueError("Quality score must be between 0 and 100")
        return v
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "exam_type": "JEE_MAIN",
                "subject": "Math",
                "topic": "Calculus",
                "difficulty": "medium",
                "min_quality_score": 80,
                "question_type": "single_correct"
            }
        }
    )


class QuestionBatch(BaseModel):
    """
    Batch of questions with statistics.
    
    This model represents a batch of questions along with aggregate
    statistics about the batch.
    
    Attributes:
        questions: List of Question objects
        total_count: Total number of questions in batch
        avg_quality_score: Average validation quality score
        topics_covered: List of unique topics covered
        generation_time: Time taken to generate batch (seconds)
    
    Example:
        >>> batch = QuestionBatch(
        ...     questions=[q1, q2, q3],
        ...     total_count=3,
        ...     avg_quality_score=85.5,
        ...     topics_covered=["Calculus", "Algebra"],
        ...     generation_time=5.2
        ... )
    """
    
    questions: List[Question] = Field(
        ...,
        description="List of questions in the batch"
    )
    
    total_count: int = Field(
        ...,
        ge=0,
        description="Total number of questions in batch"
    )
    
    avg_quality_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Average validation quality score across all questions"
    )
    
    topics_covered: List[str] = Field(
        ...,
        description="List of unique topics covered in the batch"
    )
    
    generation_time: float = Field(
        ...,
        ge=0.0,
        description="Time taken to generate batch in seconds"
    )
    
    @field_validator("total_count")
    @classmethod
    def validate_count_matches(cls, v: int, info) -> int:
        """Validate total count matches number of questions."""
        questions = info.data.get("questions", [])
        if len(questions) != v:
            raise ValueError(
                f"total_count ({v}) does not match number of questions ({len(questions)})"
            )
        return v
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "questions": [],
                "total_count": 5,
                "avg_quality_score": 85.5,
                "topics_covered": ["Limits and Continuity", "Differentiation", "Integration"],
                "generation_time": 5.2
            }
        }
    )


class GeneratedQuestionsResponse(BaseModel):
    """
    Response model for generated questions.
    
    Contains a list of generated questions along with metadata
    about the generation process.
    
    Attributes:
        questions: List of generated Question objects
        total_generated: Total number of questions generated
        total_valid: Number of valid questions
        total_invalid: Number of invalid questions
        exam_type: Type of exam questions were generated for
        topic: Topic the questions are about
        difficulty: Difficulty level of questions
    
    Example:
        >>> response = GeneratedQuestionsResponse(
        ...     questions=[question1, question2],
        ...     total_generated=2,
        ...     total_valid=2,
        ...     total_invalid=0,
        ...     exam_type="JEE_MAIN",
        ...     topic="Calculus",
        ...     difficulty="medium"
        ... )
    """
    
    questions: List[Question] = Field(
        ...,
        description="List of generated questions"
    )
    
    total_generated: int = Field(
        ...,
        description="Total number of questions generated",
        ge=0
    )
    
    total_valid: int = Field(
        ...,
        description="Number of valid questions after parsing",
        ge=0
    )
    
    total_invalid: int = Field(
        default=0,
        description="Number of invalid questions rejected",
        ge=0
    )
    
    exam_type: Optional[str] = Field(
        None,
        description="Type of exam (JEE_MAIN, JEE_ADVANCED, NEET)"
    )
    
    topic: Optional[str] = Field(
        None,
        description="Topic the questions are about"
    )
    
    difficulty: Optional[str] = Field(
        None,
        description="Difficulty level (easy, medium, hard)"
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "questions": [
                    {
                        "question": "What is the derivative of sin(2x)?",
                        "options": {
                            "A": "cos(2x)",
                            "B": "2cos(2x)",
                            "C": "-2sin(2x)",
                            "D": "2sin(2x)"
                        },
                        "correct_answer": "B",
                        "explanation": "Using chain rule: d/dx[sin(2x)] = cos(2x) × 2 = 2cos(2x)",
                        "difficulty": "easy",
                        "topic": "Calculus - Differentiation",
                        "question_type": "single_correct",
                        "marks": 4,
                        "estimated_time_minutes": 2
                    }
                ],
                "total_generated": 1,
                "total_valid": 1,
                "total_invalid": 0,
                "exam_type": "JEE_MAIN",
                "topic": "Calculus - Differentiation",
                "difficulty": "easy"
            }
        }
    )
